version: "3.8"

services:
  syncpk-server:
    image: ghcr.io/lechtung/syncpk:latest
    container_name: syncpk-server
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # Tell Python where to store everything
      - DATA_DIR=/app/data
    volumes:
      # All persistence (db, json, env and cache) will live in ./data
      - ./data:/app/data
    env_file:
      - ./data/.env